quarkus:
  console:
    color: true
  datasource:
    db-kind: postgresql
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    jdbc:
      url: ${APP_DB_HOST}
  http:
    proxy:
      allow-forwarded: true
      enable-forwarded-host: true
    host: 0.0.0.0
    port: 10000
    root-path: api
    cors:
      ~: true
      origins: https://nextjs-one-phi-76.vercel.app
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, DELETE
  hibernate-orm:
    database:
      generation: none

'%dev':
  quarkus:
    http:
      cors:
        origins: http://localhost:3000