whatsapp:
  allowedNumbers: [
    '+5511910844014',
    '+5511940785047',
    '+5511988256762'
  ]
quarkus:
  console:
    color: true
  datasource:
    db-kind: postgresql
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    jdbc:
      url: ${APP_DB_HOST}
  http:
    proxy:
      allow-forwarded: true
      enable-forwarded-host: true
    port: ${PORT:8080}
    cors:
      ~: true
      origins: https://juvini-chabar.vercel.app
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, DELETE, PATCH, PUT
  hibernate-orm:
    database:
      generation: none
  smallrye-openapi:
    info-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
    info-version: 1.0.1
    info-contact-email: vsviniciuslima@gmail.com
    info-contact-url: https://vsviniciuslima.dev/contact
    info-license-name: Apache 2.0
    info-title: E-vento
    info-description: Serviços para gerenciamento de eventos
    info-terms-of-service: Your terms here
    info-contact-name: Vinicius Santana
'%dev':
  quarkus:
    datasource:
      username: user
      password: pwd
      jdbc:
        url: jdbc:postgresql://localhost:5432/saas
    hibernate-orm:
      database:
        generation: drop-and-create
    http:
      cors:
        origins: http://localhost:3000
    live-reload:
      instrumentation: true
      watched-resources: dev.vsviniciuslima.whatsapp.connections.listeners.MessageListener
'%test':
  quarkus:
    datasource:
      db-kind: h2