quarkus:
  console:
    color: true
  datasource:
    db-kind: postgresql
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    jdbc:
      url: ${APP_DB_HOST}
  http:
    proxy:
      allow-forwarded: true
      enable-forwarded-host: true
    port: ${PORT:8080}
    cors:
      ~: true
      origins: https://juvini-chabar.vercel.app
      headers: accept, authorization, content-type, x-requested-with
      methods: GET, OPTIONS, POST, DELETE, PATCH, PUT
  hibernate-orm:
    database:
      generation: none

'%dev':
  quarkus:
    datasource:
      username: user
      password: pwd
      jdbc:
        url: jdbc:postgresql://localhost:5432/saas
    hibernate-orm:
      database:
        generation: update
    http:
      cors:
        origins: http://localhost:3000
    live-reload:
      instrumentation: true